### ISSUE TITLE
ComfoAir Q600 - all sensors "Unknown"

### ISSUE THREAD

**Issue by jrnk** [yoziru/esphome-zehnder-comfoair#18]
First of all thanks for the great work of you and others on this module :)

However I'm having trouble using this correctly in HA, all my Sensor values are "Unknown". However when the device comes online it sets 'some' values like the Balance Mode, Humidity Sensor and Temperature Profile. And it sets the Fan mode but it shows an incorrect value (Away when it should be Low).

<img width="397" alt="Screenshot 2024-07-10 at 19 52 28" src="https://github.com/yoziru/esphome-zehnder-comfoair/assets/5436814/f1676490-e9f4-4bce-b432-f4e4049b6827">

<img width="374" alt="Screenshot 2024-07-10 at 19 53 32" src="https://github.com/yoziru/esphome-zehnder-comfoair/assets/5436814/b29f1816-9199-4fc0-9be5-0f917a85daf7">

**Stack**
M5Stack AtomLite ESP32
M5Stack Mini CAN Unit (TJA1051T/3)

It's connected as [explained here](https://github.com/yoziru/esphome-zehnder-comfoair/blob/main/docs/m5stack-atoms3.md)

Built and uploaded to device with:
```bash
make compile BOARD=m5stack-atom
esphome upload zehnder-comfoair-q-m5stack-atom.yml
```

Note: `make upload` didn't work as it kept defaulting to uploading through the network instead of usb.

My hunch was that the protocol is slightly different for the Q600 than the Q350, but looking at https://github.com/michaelarnauts/aiocomfoconnect/blob/master/docs/PROTOCOL-PDO.md it should be the same.

Any suggestions / reasons this might not work?

**Comment by yoziru** [comment]
I think you're using the wrong board, it should be `m5stack-atoms3` instead of `m5stack-atom`
- `make upload` should be fixed now (https://github.com/yoziru/esphome-zehnder-comfoair/commit/8000fb4101161752bc75dc4dfbb4a690beadf09b), and you should be able to select a USB device when connected
- You can also try flashing from https://yoziru.github.io/esphome-zehnder-comfoair/ using Chrome (without needing to compile)

If after setting the right board it still doesn't work, I would double-check your jumper cables

**Comment by jrnk** [comment]
Thanks, the image is for the board but yes, my hunch was the cable connection too but they are exactly connected as per the instructions:

![image](https://github.com/user-attachments/assets/99cc1e3c-1b59-4f39-9a80-203d47eab4af)

![image](https://github.com/user-attachments/assets/c804e608-0a77-4fb6-8833-bfeb0f26e16d)

Maybe the cable is faulty 🤔, I will try to check the raw CAN communication first if I figure out how to do that :)

**Comment by yoziru** [comment]
That looks right to me, and given your CAN adapter light is on the power is coming through normally.
You are using both CAN buses on the Zehnder so don't know if that makes a difference.

The only other thing I can think of is that the rx tx GPIO pins are set wrong for the board (which is possible since I didn't test the regular Atom Lite). You could try modifying those to another pin and see if that makes a difference.

https://github.com/yoziru/esphome-zehnder-comfoair/blob/dd5e2062868c628e705b94036b91100799fd4171/boards/m5stack-atom.yml#L2

Alternative would be to get an Atom S3 Lite and test if that board works to eliminate the cable or the 2nd CAN bus being the problem

**Comment by jrnk** [comment]
Thanks so much, it is indeed fixed now. Only had to tweak the flash size, will open a PR for this
